on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Get Shellspec
        run: curl -fsSL https://git.io/shellspec | tee >(sha256sum) | sh -s -- --yes

      - name: Shellspec
        run: shellspec --output junit

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Unit Test Results
          path: report/*.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: report/*.xml